Vagrant.configure("2") do |config|

  config.vm.define "source", autostart: false do |source|
	  source.vm.box = "#{ENV["SRC_IMAGE_NAME"]}"
    source.vm.box_version = "#{ENV["SRC_IMAGE_VERSION"]}"
	  config.ssh.insert_key = {{.InsertKey}}
  end

  config.vm.define "output" do |output|
	  output.vm.box = "{{.BoxName}}"
	  output.vm.box_url = "file://package.box"
	  config.ssh.insert_key = {{.InsertKey}}
  end

  config.vm.synced_folder "..", "/vagrant"

end