Vagrant.configure("2") do |config|

    $basebox_name="elegoev-ubuntu-18.04-ansible-test"
    $basebox_hostname="ubuntu-1804-ansible-test"
    $src_image_name="elegoev/ubuntu-18.04-ansible"
    $src_image_version="2.0.1609256225"

    config.vm.define "#{$basebox_name}" do |machine|
      machine.vm.box = "#{$src_image_name}"
      machine.vm.box_version = "#{$src_image_version}"
    
      # define guest hostname
      machine.vm.hostname = "#{$basebox_hostname}"

      machine.vm.provider "virtualbox" do |vb|
        vb.name = $basebox_name
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--memory", "1024" ]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--groups", "/basebox-test" ]
        vb.customize ["modifyvm", :id, "--vram", 256 ]
      end

    end   

end
  